version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI
    networks:
      - symfony_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - ./app:/var/www/html
      - ./logs:/var/www/logs
    working_dir: /var/www/html
    depends_on:
      - db
      - rabbitmq  # Depends on RabbitMQ instead of Kafka
    networks:
      - symfony_network

  web:
    image: nginx:alpine
    container_name: symfony_web
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony_network

  db:
    image: mariadb:latest
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: legal
      MYSQL_USER: legal
      MYSQL_PASSWORD: legal
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  db_data:
